# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
x_o = True

all_buttons = []


class Ui_Widget(object):
    def setupUi(self, Widget):
        global all_buttons
        Widget.setObjectName("Widget")
        Widget.resize(781, 661)
        self.but1 = QtWidgets.QPushButton(Widget)
        self.but1.setGeometry(QtCore.QRect(0, 0, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but1.setFont(font)
        self.but1.setText("")
        self.but1.setObjectName("but1")
        all_buttons.append(self.but1)
        self.but2 = QtWidgets.QPushButton(Widget)
        self.but2.setGeometry(QtCore.QRect(260, 0, 261, 221))
        
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but2.setFont(font)
        self.but2.setText("")
        self.but2.setObjectName("but2")
        all_buttons.append(self.but2)
     
        self.but3 = QtWidgets.QPushButton(Widget)
        self.but3.setGeometry(QtCore.QRect(520, 0, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but3.setFont(font)
        self.but3.setText("")
        self.but3.setObjectName("but3")
        all_buttons.append(self.but3)
        self.but4 = QtWidgets.QPushButton(Widget)
        self.but4.setGeometry(QtCore.QRect(0, 220, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but4.setFont(font)
        self.but4.setText("")
        self.but4.setObjectName("but4")
        all_buttons.append(self.but4)
        self.but5 = QtWidgets.QPushButton(Widget)
        self.but5.setGeometry(QtCore.QRect(260, 220, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but5.setFont(font)
        self.but5.setText("")
        self.but5.setObjectName("but5")
        all_buttons.append(self.but5)
        self.but6 = QtWidgets.QPushButton(Widget)
        self.but6.setGeometry(QtCore.QRect(520, 220, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but6.setFont(font)
        self.but6.setText("")
        self.but6.setObjectName("but6")
        all_buttons.append(self.but6)
        self.but7 = QtWidgets.QPushButton(Widget)
        self.but7.setGeometry(QtCore.QRect(0, 440, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but7.setFont(font)
        self.but7.setText("")
        self.but7.setObjectName("but7")
        all_buttons.append(self.but7)
        self.but8 = QtWidgets.QPushButton(Widget)
        self.but8.setGeometry(QtCore.QRect(260, 440, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but8.setFont(font)
        self.but8.setText("")
        self.but8.setObjectName("but8")
        all_buttons.append(self.but8)
        self.but9 = QtWidgets.QPushButton(Widget)
        self.but9.setGeometry(QtCore.QRect(520, 440, 261, 221))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.but9.setFont(font)
        self.but9.setText("")
        self.but9.setObjectName("but9")
        all_buttons.append(self.but9)
        
       
        
      
        
        self.add_functions()
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def add_functions(self):
        self.but1.clicked.connect(lambda : self.set_box(self.but1))
        self.but2.clicked.connect(lambda : self.set_box(self.but2))
        self.but3.clicked.connect(lambda : self.set_box(self.but3))
        self.but4.clicked.connect(lambda : self.set_box(self.but4))
        self.but5.clicked.connect(lambda : self.set_box(self.but5))
        self.but6.clicked.connect(lambda : self.set_box(self.but6))
        self.but7.clicked.connect(lambda : self.set_box(self.but7))
        self.but8.clicked.connect(lambda : self.set_box(self.but8))
        self.but9.clicked.connect(lambda : self.set_box(self.but9))


    def set_box(self,obj):
        global x_o
        
        if obj.text() != "":
            error = QMessageBox()
            error.setWindowTitle("Error")
            error.setText("Invalid action")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)
            error.exec_()
            return False
        else:
            obj.setText("X" if x_o == True else "O")
            obj.setStyleSheet("color:red;" if x_o == True else "color:green;")

        x_o = False if x_o == True else True

        self.check_won()
        return True


    def check_won(self):
        cond = False
        player = ""
        if all_buttons[0].text() == all_buttons[1].text() == all_buttons[2].text() and all_buttons[0].text() != "":
            cond = True
            player = all_buttons[0].text()
        elif all_buttons[3].text() == all_buttons[4].text() == all_buttons[5].text() and all_buttons[3].text() != "":
            cond = True
            player = all_buttons[3].text()
        elif all_buttons[6].text() == all_buttons[7].text() == all_buttons[8].text() and all_buttons[6].text() != "":
            cond = True
            player = all_buttons[6].text()
        elif all_buttons[0].text() == all_buttons[3].text() == all_buttons[6].text() and all_buttons[0].text() != "":
            player = all_buttons[0].text()
            cond = True
        elif all_buttons[1].text() == all_buttons[4].text() == all_buttons[7].text() and all_buttons[1].text() != "":
            cond = True
            player = all_buttons[1].text()
        elif all_buttons[2].text() == all_buttons[5].text() == all_buttons[8].text() and all_buttons[2].text() != "":
            cond = True
            player = all_buttons[2].text()
        elif all_buttons[0].text() == all_buttons[4].text() == all_buttons[8].text() and all_buttons[0].text() != "":
            cond = True
            player = all_buttons[0].text()
        elif all_buttons[2].text() == all_buttons[4].text() == all_buttons[6].text() and all_buttons[2].text() != "":
            cond = True
            player = all_buttons[2].text()           
        if cond == True:
            wining = QMessageBox()
            wining.setWindowTitle("Tic-Tac-Toe")
            wining.setText("Player " + player + " is winner!!!")
            wining.setStandardButtons(QMessageBox.Ok)
            wining.exec_()
            Widget.close()

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    global Widget
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
